package katkit.uz.startupcafe.enums;

public enum ButtonKey {
    PROJECTS, PROJECT_FIND, PROFILE, SIGN_UP, PROJECT_CREATE,
    //General
    BACK, HOME,
    //Sign up
    CONTACT, CONFIRM,
    // Profile (Cabinet)
    CHANGE_NAME,CHANGE_PHONE,CHANGE_BIO, CHANGE_PROFESSION, PROFILE_INFORMATION, PROFILE_EDIT, SKIP, CANCEL, MY_PROJECT, OFFICE, PROJECT_JOINED, STATISTICS, EDIT_PROJECTS, POST_CREATE,

}
