package katkit.uz.startupcafe.enums;


public enum SentenceKey {
    START, RESTART, HELP, LANGUAGE, SUBSCRIBE, CHECK, LANGUAGE_CHANGED, HOME,
    //Sign Up - Profile(Cabinet)
    REQUEST_CONTACT, REQUEST_BIO, REQUEST_NAME, REQUEST_PROFESSION,
    SIGN_UP_CONFIRM, SIGN_UP_CANCEL,
    //Information shablon
    NAME, PHONE_NUMBER, INFORMATION,
    NUMBER_CHANGED, //Profile (Cabinet)
    NAME_CHANGED, BIO_CHANGED, PROFESSION_CHANGED, PROFILE, PROFILE_EDIT,
    // Project create
    PROJECT_CREATE, FIND_PROJECT, REGISTER, INCORRECT_ID, PROJECT_NOT_FOUND, PROJECT_DESCRIPTION, PROJECT_PHOTO,
    PROJECT_CREATE_CONFIRM, PROJECT_CREATE_CANCEL, PROJECT_CREATE_FINISHED,
    PROJECT_CREATE_INFORMATION, PROJECT_CREATE_TECHNOLOGIES, TECHNOLOGIES_NULL, IS_IT_TRUE, OFFICE, MY_PROJECT_EMPTY, DELETE, JOIN, PROJECT_EMPTY, ITS_YOURS_PROJECT, PROJECT_INFORMATION, CONNECT, CREATOR, BACK, ADD, REJECT, JOIN_REQUEST, JOIN_REQUEST_ACCEPTED, JOIN_REQUEST_REJECTED, START_ADMIN, PROJECT_DELETED_BY_ADMIN, STATISTIC, POST_REQUEST,

}