package katkit.uz.startupcafe.enums;



public enum Step {
    PROJECT_FIND, PROJECT, SIGN_UP, MAIN,

    // Sign up
    SIGN_UP_NAME, SIGN_UP_CONTACT, SIGN_UP_BIO, SIGN_UP_CONFIRM, PROFILE, SIGN_UP_PROFESSION,

    PROFILE_EDIT_NAME, PROFILE_EDIT_PHONE, PROFILE_EDIT_BIO, PROFILE_EDIT_PROFESSION,
    PROFILE_EDIT,


    //Project
    PROJECT_CREATE, PROJECT_CREATE_DESCRIPTION, PROJECT_CREATE_ATTACH, PROJECT_CREATE_CONFIRM, PROJECT_CREATE_TECHNOLOGIES,

    POST_SEND, OFFICE



}
